### ISSUE TITLE
Running on my dataset

### ISSUE THREAD

**Issue by Carinazhao22** [zhengqili/Neural-Scene-Flow-Fields#10]
Hi, I want to run nsff on my dataset. When I run the preprocessing section on my dataset, motion_masks are all white. Does that mean there are some issues with my dataset or maybe I cannot run it with my dataset? How can I solve it? Thanks! 
![f229cf6bb9297d77c8ccf0a433e4b5b](https://user-images.githubusercontent.com/52422263/113624306-508f1a00-9614-11eb-9661-41f2459a641e.jpg)

**Comment by zhengqili** [comment]
Hi, What do the input images look like?

**Comment by Carinazhao22** [comment]
Hi, here is the link for my data. Thank you! 
[https://drive.google.com/file/d/1bpCAWqoC1BxC8L0p2joy3WNEFnYm7U4h/view?usp=sharing](url)

**Comment by Carinazhao22** [comment]
Hi, you can just look at my screenshots. Thanks. 
![b13351cbc3ca3f5af886ae7ddbe3b9f](https://user-images.githubusercontent.com/52422263/113658258-8bb13d80-9654-11eb-8fa6-16e76061f62a.png)
![73d192aae893e843259e0fe09a20138](https://user-images.githubusercontent.com/52422263/113658278-8fdd5b00-9654-11eb-823e-55d9632d5ffa.png)
![87d4edc2d3fdc81c1a05e3baa009dbf](https://user-images.githubusercontent.com/52422263/113658287-966bd280-9654-11eb-8bc3-41d13319e1de.png)
![8abd156f93446ec80ebb431b2326720](https://user-images.githubusercontent.com/52422263/113658304-a1befe00-9654-11eb-8cc6-118da3bf6791.png)
![5c320e69e5a75de8a3f566642ec7a68](https://user-images.githubusercontent.com/52422263/113658319-ad122980-9654-11eb-900e-7f038d688cbd.png)
![9648b99a23fa7f8e72961b72056e277](https://user-images.githubusercontent.com/52422263/113658331-b3080a80-9654-11eb-8206-7007fd74a842.png)

**Comment by owang** [comment]
The current pipeline is set up for data that comes from a single camera, and computes optical flow between subsequent frames. To handle multiview data like you have here, you would need to add support to only compute and use optical flow calculated between subsequent frames of the same camera.

**Comment by Carinazhao22** [comment]
Thank you! I got it.

**Comment by HarshaMupparaju** [comment]
@Carinazhao22 , did your dataset consists of a multiview setup? If so, could you run their model on the multiview setup?
