### ISSUE TITLE
Multi-gpu training

### ISSUE THREAD

**Issue by kwea123** [zhengqili/Neural-Scene-Flow-Fields#2]
In readme you say it takes 2 days on 2 V100 gpus, but I don't see any option setting the number of gpus to use in `run_nerf.py`. Does it mean this code only supports single gpu training?

**Comment by zhengqili** [comment]
It by default detect all the GPUs in your machine and use all of them to train the model.

**Comment by Achleshwar** [comment]
@zhengqili I am curious to know how you set this type of multi-gpu training. If you can share any relevant resource or point me to the code block where this operation is happening, that would be great. Thank you!
