### ISSUE TITLE
README Demo Not Working

### ISSUE THREAD

**Issue by rohaldb** [zhengqili/Neural-Scene-Flow-Fields#20]
Hi, 

I believe there is an issue with the demo as outlined in the readme. Specifically, when trying to use the pre-trained model to render *any* of the 3 interpolation methods - time, viewpoint, or both - the resulting images (as found in `nsff_exp/logs/kid-running_ndc_5f_sv_of_sm_unify3_testing_F00-30/<interpolation_dependent_name>/images`) come out looking like this: 

![5409d20a-cc1a-49fb-844b-2f74691ab620](https://user-images.githubusercontent.com/30969082/122717353-d84d0200-d2ae-11eb-9e95-29a50ac0d985.jpeg)
or
![49da9f71-2949-45b9-addd-7352e925ec48](https://user-images.githubusercontent.com/30969082/122718035-c586fd00-d2af-11eb-9b8c-c3182db4495d.jpeg)
depending on which form of interpolation I run.

I have a [colab file](https://colab.research.google.com/drive/1x1i_uQnbTywZ-cr_z357laJc49sUJ38Q?usp=sharing) set up that obtains the above result. It pulls from a forked repository which has only [two changes](https://github.com/rohaldb/Neural-Scene-Flow-Fields/commit/7c33494bda0f6452faf36802df2319f04fca6d89): I add a requirements.txt file and update the `data_dir` in `nsff_exp/configs/config_kid-running.txt`. 

Have I missed something or am I correct in saying the demo broken? Thanks!

**Comment by knelk** [comment]
same issue here - got the suspicion it is due to pytorch/torchvision/cudatoolkit  installation. when using  torchvision 0.8.1 I also get those artefact images, when using torchvision 0.2 I get black images. I am on Ubuntu18.04 with torchvision 0.8.1, pytorch 1.7.0 and cudatoolkit 11.0.221.

What is your environment? Which conda version etc you are using?

**Comment by knelk** [comment]
the issue is with the folder name check issue #13
