### ISSUE TITLE
Coordinate System Operations

### ISSUE THREAD

**Issue by rohaldb** [zhengqili/Neural-Scene-Flow-Fields#22]
Hi team, amazing paper!  

I am trying to adapt your model to regularise the volume-rendered scene flow against a monocular scene flow estimator from a different paper. The third-party scene flow estimator produces results in world coordinates (not normalised) so for me to compare against this model's scene flow, which is in NDC space, I need to transform one coordinate system to the other. This has me confused by some of the code you use to do coordinate system conversions. 

1. Firstly, in the supplementary document, and in the code, you reference "euclidean space". I couldn't find anything online about whether this is world space or camera space. Could you please clarify? 
2. The supplementary document references the NDC ray space derivation from the NeRF paper. That derivation outlines how to convert points from camera space (`o`) to NDC space (`o'`): 
![Screen Shot 2021-07-14 at 12 39 21 pm](https://user-images.githubusercontent.com/30969082/125552135-08a2a70f-45bc-4059-9e7e-0f6d39175709.png)
Following this, I found this function, which appears to do the inverse operation of eq 25 above. 
https://github.com/zhengqili/Neural-Scene-Flow-Fields/blob/562049433ddb3e3dee620f2247f4173f74e03438/nsff_exp/run_nerf_helpers.py#L534-L541
That is, it converts from NDC to what I can conclude must be camera space. However, when I look at its invocation, the variable name suggests that this function converts from NDC to world coordinates
https://github.com/zhengqili/Neural-Scene-Flow-Fields/blob/562049433ddb3e3dee620f2247f4173f74e03438/nsff_exp/run_nerf_helpers.py#L552
3. Following this, the pipeline to project from 3d NDC to a 2d image has me quite confused:
https://github.com/zhengqili/Neural-Scene-Flow-Fields/blob/562049433ddb3e3dee620f2247f4173f74e03438/nsff_exp/run_nerf_helpers.py#L546-L563
a) I assume `se3_transform_points` converts from world space to camera space, is that correct? 
b) Why do you perform the perspective projection from camera space? Everything I have read online seems to perform perspective projection from either world coordinates / ndc. 

Generally, it would be very helpful to me if you could point me to where you obtained the operations for `perspective_projection`, `se3_transform_points` and `NDC2Euclidean`. 

My graphics knowledge is limited so apologies if these questions are trivial. Your help is greatly appreciated :)

**Comment by kwea123** [comment]
Like the variable name `pts_3d_e_world` suggests, `NDC2Euclidean` converts from NDC to world coordinates.
a) Correct.
b) Perspective projection can be done from either camera space or world space. There is a good [tutorial](http://opencv.jp/opencv-2.1_org/py/camera_calibration_and_3d_reconstruction.html) on opencv. Cam2Img is just multiplying by `K`, while World2Img needs [R|T] in the middle, that's all the difference.

In graphics you only need to know what intrinsics and extrinsics stand for, and how to use them to convert between img/camera/world coordinates.

**Comment by rohaldb** [comment]
Thanks so much @kwea123 ! 
That is great news, it means I should just be able to perform volume rendering along each ray to obtain per-pixel scene flow estimates, pass those through `NDC2Euclidean` and compare the results to my third party per pixel scene flow estimator 😊

**Comment by rohaldb** [comment]
For any others viewing this, please see https://github.com/bmild/nerf/issues/35
