### ISSUE TITLE
Implementation different from paper?

### ISSUE THREAD

**Issue by Guptajakala** [zhengqili/Neural-Scene-Flow-Fields#37]
https://github.com/zhengqili/Neural-Scene-Flow-Fields/blob/d4001759a39b056c95d8bc22da34b10b4fb85afb/nsff_exp/render_utils.py#L487

Here the network only takes input of points and view directions and predicts the forward and backward flow to neighbor frames. But in paper eq(4), the network additionally needs the time `i`. Is the `i` not useful in practice? 

If that's the case, I'm wondering how the network can distinguish the different frames, if there are some points and view dirs that happen to be the same in different frames.

**Comment by violetamenendez** [comment]
Hi,

I am not the owner, but the time is concatenated to the points before feeding it to the network. Just a few lines before, in here:

https://github.com/zhengqili/Neural-Scene-Flow-Fields/blob/d4001759a39b056c95d8bc22da34b10b4fb85afb/nsff_exp/render_utils.py#L477

**Comment by Guptajakala** [comment]
@violetamenendez can't believe I missed that! Thanks a lot!
