### ISSUE TITLE
Evaluation metrics

### ISSUE THREAD

**Issue by kwea123** [zhengqili/Neural-Scene-Flow-Fields#6]
Hi, I am wondering if there is a standard for SSIM and LPIPS.

For SSIM: I see you use the implementation of scikit-image. When I use kornia's implementation with window size = 11 (I don't know what size scikit-image uses if it's not set), it seems to yield different result... Do you have idea what other authors use?

For LPIPS:
1. Do the other authors also use alexnet?
2. https://github.com/zhengqili/Neural-Scene-Flow-Fields/blob/62a1770db37ae9d927cdd2c43918263da43d7efa/nsff_exp/evaluation.py#L326
   The network expects the rgb to be scaled to [-1, 1]. If it's [0, 1] it seems that you need to pass argument `normalize=True`
   https://github.com/zhengqili/Neural-Scene-Flow-Fields/blob/62a1770db37ae9d927cdd2c43918263da43d7efa/nsff_exp/models/__init__.py#L26-L34
   So I'm afraid the evaluation you have is not exactly correct...

It makes me think that if there's no common standard for these metrics that might differ from one implementation to the other, or that sometimes the authors make mistake in the evaluation process, then only the PSNR score is credible...

**Comment by zhengqili** [comment]
Hi Thanks. 

In evaluation code, I did normalize them to [-1, 1] before passing the LPIPS:
                gt_img_0 = im2tensor(gt_img).cuda()
                rgb_0 = im2tensor(rgb).cuda()

This is the same as original demo from LPIPS: https://github.com/richzhang/PerceptualSimilarity/blob/master/lpips_2imgs.py

In terms of  SSIM, I believe I use the evaluation code from implementation from paper "Pushing the Boundaries of View Extrapolation with Multiplane Images" (Although it seems that they update the code recently so It no longer has evaluation part.....)
